name: jira-comment
description: Comments on the given Jira ticket
source: github.com/deepikasl/pipe-task-hello-world
labels:
  - jira
  - comment
input:
  - name: issue_key
    description: key of the jira issue where you want to add a comment
  - name: endpoint
    description: url of the jira
  - name: username
    description: username of the jira
  - name: token
    description: token
  - name: comment
    description: comment which you want to add in ticket
execution:
  - node16 src/index.js